// Fallback data when Airtable is not configured
// This allows the site to work in preview/development mode

import type { Profile, ProfileSummary, ExperienceRecord } from "./airtable"

export const fallbackProfiles: ProfileSummary[] = [
  {
    profileId: "BW001",
    slug: "bespoke-windows-london",
    businessName: "Bespoke Windows London",
    location: "London",
    category: "Windows & Doors",
    tags: ["Sash Windows", "Double Glazing", "Triple Glazing", "Composite Doors", "Bay Windows", "Period Property"],
    overallScore: 9.2,
    sampleSize: 18,
    dateRange: "Jan–Jun 2025",
    logoUrl: "/images/bw-20logo-20small.png",
    shortDescription: "Premium window and door installations with consistently high workmanship ratings.",
    website: "https://bespokewindows.co.uk",
  },
  {
    profileId: "GL002",
    slug: "greenleaf-landscapes",
    businessName: "Greenleaf Landscapes",
    location: "Surrey",
    category: "Landscaping & Gardens",
    tags: ["Garden Design", "Landscaping", "Paving", "Fencing"],
    overallScore: 8.9,
    sampleSize: 24,
    dateRange: "Feb–Jun 2025",
    shortDescription: "Garden design and landscaping services with strong communication and project management.",
    website: "https://greenleaflandscapes.co.uk",
  },
  {
    profileId: "AR003",
    slug: "apex-roofing-solutions",
    businessName: "Apex Roofing Solutions",
    location: "Manchester",
    category: "Roofing",
    tags: ["Roof Repair", "Flat Roofing", "Slate Roofing", "Guttering"],
    overallScore: 9.4,
    sampleSize: 31,
    dateRange: "Jan–Jun 2025",
    shortDescription: "Residential and commercial roofing with exceptional reliability scores.",
    website: "https://apexroofing.co.uk",
  },
  {
    profileId: "CE004",
    slug: "clarity-electrical",
    businessName: "Clarity Electrical",
    location: "Birmingham",
    category: "Electrical Services",
    tags: ["Rewiring", "Consumer Units", "Lighting", "EV Charging"],
    overallScore: 8.7,
    sampleSize: 42,
    dateRange: "Mar–Jun 2025",
    shortDescription: "Domestic electrical work with consistently punctual and tidy service delivery.",
    website: "https://clarityelectrical.co.uk",
  },
  {
    profileId: "HK005",
    slug: "heritage-kitchens",
    businessName: "Heritage Kitchens",
    location: "Bristol",
    category: "Kitchen Installation",
    tags: ["Bespoke Kitchens", "Kitchen Fitting", "Worktops"],
    overallScore: 9.1,
    sampleSize: 15,
    dateRange: "Jan–May 2025",
    shortDescription: "Bespoke kitchen design and fitting with high attention to detail.",
    website: "https://heritagekitchens.co.uk",
  },
  {
    profileId: "CP006",
    slug: "clearview-plumbing",
    businessName: "Clearview Plumbing & Heating",
    location: "Leeds",
    category: "Plumbing & Heating",
    tags: ["Boiler Installation", "Central Heating", "Plumbing", "Gas Safe"],
    overallScore: 8.5,
    sampleSize: 56,
    dateRange: "Jan–Jun 2025",
    shortDescription: "Boiler installations and general plumbing with responsive customer service.",
    website: "https://clearviewplumbing.co.uk",
  },
  {
    profileId: "OB007",
    slug: "oakwood-builders",
    businessName: "Oakwood Builders",
    location: "Edinburgh",
    category: "Construction & Extensions",
    tags: ["Extensions", "Renovations", "Loft Conversions", "New Build"],
    overallScore: 9.3,
    sampleSize: 12,
    dateRange: "Feb–Jun 2025",
    shortDescription: "Home extensions and renovations with excellent project communication.",
    website: "https://oakwoodbuilders.co.uk",
  },
  {
    profileId: "PD008",
    slug: "premier-decorators",
    businessName: "Premier Decorators",
    location: "Liverpool",
    category: "Painting & Decorating",
    tags: ["Interior Painting", "Exterior Painting", "Wallpapering"],
    overallScore: 8.8,
    sampleSize: 38,
    dateRange: "Jan–Jun 2025",
    shortDescription: "Interior and exterior painting with consistent quality finishes.",
    website: "https://premierdecorators.co.uk",
  },
  {
    profileId: "SS009",
    slug: "secure-systems-uk",
    businessName: "Secure Systems UK",
    location: "Reading",
    category: "Security Systems",
    tags: ["CCTV", "Alarm Systems", "Smart Home", "Access Control"],
    overallScore: 9.0,
    sampleSize: 27,
    dateRange: "Mar–Jun 2025",
    shortDescription: "Alarm and CCTV installation with thorough customer education.",
    website: "https://securesystemsuk.co.uk",
  },
  {
    profileId: "PF010",
    slug: "perfect-floors",
    businessName: "Perfect Floors",
    location: "Newcastle",
    category: "Flooring",
    tags: ["Hardwood Flooring", "Laminate", "Tile Flooring", "Vinyl"],
    overallScore: 8.6,
    sampleSize: 33,
    dateRange: "Feb–Jun 2025",
    shortDescription: "Hardwood, laminate, and tile flooring with clean installation practices.",
    website: "https://perfectfloors.co.uk",
  },
]

export const fallbackProfileDetails: Record<string, Profile> = {
  "bespoke-windows-london": {
    profileId: "BW001",
    slug: "bespoke-windows-london",
    businessName: "Bespoke Windows London",
    location: "London",
    category: "Windows & Doors",
    tags: ["Sash Windows", "Double Glazing", "Triple Glazing", "Composite Doors", "Bay Windows", "Period Property"],
    overallScore: 9.2,
    sampleSize: 18,
    dateRange: "Jan–Jun 2025",
    logoUrl: "/images/bw-20logo-20small.png",
    website: "https://bespokewindows.co.uk",
    summary:
      "Customers consistently highlight workmanship quality and installer professionalism. Communication is rated highly, with a small number of customers noting that scheduling updates could be clearer during busy periods.",
    scores: {
      productSatisfaction: 9.5,
      installationSatisfaction: 9.1,
      processCommunication: 8.8,
      likelihoodToRecommend: 9.2,
    },
    consistencySignals: {
      highScorePercentage: 94,
      recommendationRate: 92,
      topThemes: ["Professionalism", "Quality", "Cleanliness"],
    },
    customerVoice: [
      { quote: "We noticed the difference in warmth immediately.", name: "Sarah" },
      { quote: "Install team were tidy and professional.", name: "Michael" },
      { quote: "Would have liked slightly clearer timing updates, but the end result is excellent.", name: "Emma" },
      { quote: "The windows have transformed our front room.", name: "David" },
      { quote: "Straightforward process from survey to completion.", name: "Claire" },
      { quote: "Good value for the quality we received.", name: "James" },
    ],
    services: [
      "Double glazed window installation",
      "Triple glazed window installation",
      "Composite door fitting",
      "Bay window installation",
      "Sash window replacement",
      "French door installation",
      "Bi-fold door installation",
      "Window repairs and maintenance",
      "Energy efficiency upgrades",
      "Period property window restoration",
    ],
    baseLocation: "London",
    areasCovered: ["South West London", "Central London", "Surrey"],
    externalPresence: {
      platform1Name: "Google",
      platform1ReviewCount: 312,
      platform1Url: "https://g.page/bespoke-windows-london",
      platform2Name: "Checkatrade",
      platform2ReviewCount: 146,
      platform2Url: "https://www.checkatrade.com/trades/bespokewindows",
    },
  },
}

export const fallbackRecords: Record<string, ExperienceRecord[]> = {
  "bespoke-windows-london": [
    {
      customerLabel: "Sarah (SW11)",
      date: "2025-06-15",
      headline: "Full window replacement across ground floor",
      projectType: "Double glazing installation",
      overallScore: 9.4,
      summaryPublic: "Complete ground floor window replacement including living room, dining room, and kitchen. Exceptional attention to finishing details and minimal disruption to daily routine.",
      sentiment: "positive",
      tags: ["Quality", "Professional", "Tidy"],
      ratings: {
        productSatisfaction: 9.5,
        installationSatisfaction: 9.6,
        processCommunication: 9.0,
        likelihoodToRecommend: 9.5,
      },
      behaviouralNote: "Already recommended to neighbours.",
      customerNote: "The fitters were really careful around our furniture and cleaned up everything at the end of each day.",
    },
    {
      customerLabel: "Michael (W4)",
      date: "2025-05-22",
      headline: "Bay window installation",
      projectType: "Bay window installation",
      overallScore: 9.1,
      summaryPublic: "Single bay window installation in period property. Completed on schedule with careful attention to preserving original features.",
      sentiment: "positive",
      tags: ["On Schedule", "Period Property"],
      ratings: {
        productSatisfaction: 9.2,
        installationSatisfaction: 9.0,
        processCommunication: 9.0,
        likelihoodToRecommend: 9.2,
      },
    },
    {
      customerLabel: "Emma (N1)",
      date: "2025-05-08",
      headline: "Double glazing upgrade",
      projectType: "Double glazing upgrade",
      overallScore: 8.6,
      summaryPublic: "Upgrade from single to double glazing across three bedrooms. Final result met expectations despite minor scheduling delay during initial coordination.",
      sentiment: "mixed",
      tags: ["Energy Efficiency", "Scheduling"],
      ratings: {
        productSatisfaction: 9.0,
        installationSatisfaction: 8.8,
        processCommunication: 7.8,
        likelihoodToRecommend: 8.8,
      },
      behaviouralNote: "Scheduling confirmation could be quicker.",
      companyActionNote: "We have since improved our scheduling confirmation process to provide clearer timelines within 24 hours of booking.",
      companyActionNoteApproved: true,
    },
    {
      customerLabel: "David (SE22)",
      date: "2025-04-18",
      headline: "Composite door installation",
      projectType: "Composite door fitting",
      overallScore: 9.5,
      summaryPublic: "Premium composite front door with sidelights. Customer praised both product quality and installer conduct throughout the project.",
      sentiment: "positive",
      tags: ["Quality", "Professional", "Front Door"],
      ratings: {
        productSatisfaction: 9.7,
        installationSatisfaction: 9.5,
        processCommunication: 9.4,
        likelihoodToRecommend: 9.4,
      },
      customerNote: "The door completely transformed our entrance. Everyone comments on it.",
    },
    {
      customerLabel: "Claire (E17)",
      date: "2025-03-25",
      headline: "Full house window replacement",
      projectType: "Sash window replacement",
      overallScore: 9.2,
      summaryPublic: "Complete house window replacement completed over two days. Team described as courteous and efficient with thorough cleanup.",
      sentiment: "positive",
      tags: ["Full House", "Efficient", "Clean"],
      ratings: {
        productSatisfaction: 9.3,
        installationSatisfaction: 9.2,
        processCommunication: 9.0,
        likelihoodToRecommend: 9.3,
      },
      customerNote: "We noticed the difference in noise levels immediately. So much quieter now.",
    },
    {
      customerLabel: "James (NW3)",
      date: "2025-02-12",
      headline: "Kitchen and utility windows",
      projectType: "Double glazing installation",
      overallScore: 9.0,
      summaryPublic: "Kitchen and utility room window replacement. Completed within quoted timeframe with careful protection of kitchen surfaces.",
      sentiment: "positive",
      tags: ["On Time", "Careful"],
      ratings: {
        productSatisfaction: 9.0,
        installationSatisfaction: 9.0,
        processCommunication: 8.8,
        likelihoodToRecommend: 9.2,
      },
    },
    {
      customerLabel: "Robert (SW19)",
      date: "2025-01-28",
      headline: "Front door and sidelights",
      projectType: "Composite door fitting",
      overallScore: 8.9,
      summaryPublic: "Front door replacement with matching sidelights. Customer satisfied with product and fitting quality after minor post-installation adjustment.",
      sentiment: "positive",
      tags: ["Front Door", "Responsive"],
      ratings: {
        productSatisfaction: 9.0,
        installationSatisfaction: 8.6,
        processCommunication: 8.8,
        likelihoodToRecommend: 9.2,
      },
      behaviouralNote: "Minor adjustment needed post-install, resolved promptly.",
    },
  ],
}

// Generate fallback profile details for all profiles
fallbackProfiles.forEach((profile) => {
  if (!fallbackProfileDetails[profile.slug]) {
    fallbackProfileDetails[profile.slug] = {
      ...profile,
      summary: `${profile.businessName} provides ${profile.category.toLowerCase()} services in ${profile.location}. ${profile.shortDescription}`,
      scores: {
        productSatisfaction: profile.overallScore + (Math.random() * 0.4 - 0.2),
        installationSatisfaction: profile.overallScore - 0.1 + Math.random() * 0.2,
        processCommunication: profile.overallScore - 0.4 + Math.random() * 0.3,
        likelihoodToRecommend: profile.overallScore - 0.2 + Math.random() * 0.2,
      },
      consistencySignals: {
        highScorePercentage: Math.round(85 + Math.random() * 10),
        recommendationRate: Math.round(88 + Math.random() * 10),
        topThemes: ["Professionalism", "Quality", "Communication"].slice(0, 2 + Math.floor(Math.random() * 2)),
      },
      customerVoice: [
        { quote: "Very happy with the work completed.", name: "Customer" },
        { quote: "Professional team from start to finish.", name: "Customer" },
        { quote: "Would definitely use again.", name: "Customer" },
      ],
    }
  }
})
